name: Deploy to Server

on: workflow_dispatch

env:
  DOCKER_IMAGE: rita
  VERSION: '1.0'
  HOST_NAME: 'https://rita.britad.com'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Define build version
        id: default-version
        run: echo "TAG_VERSION=${GITHUB_RUN_ID}" >> $GITHUB_ENV

      - name: Build docker image
        id: build-docker
        run: docker build --load -t "${{env.DOCKER_IMAGE}}:${{env.VERSION}}.${{env.TAG_VERSION}}" .

      - name: Stop old container if exists
        run: |
          docker stop "${{env.DOCKER_IMAGE}}" || true
          docker rm "${{env.DOCKER_IMAGE}}" || true

      - name: Deploy new container
        run: |
          docker run -d \
            --name "${{env.DOCKER_IMAGE}}" \
            --network main_network \
            --restart=always \
            -p 3700:3000 \
            -e DATABASE_URL="${{secrets.DATABASE_URL}}" \
            -e CHANNEL_ID="${{secrets.CHANNEL_ID}}" \
            -e CHANNEL_SECRET="${{secrets.CHANNEL_SECRET}}" \
            -e IOT_INVOKE_SECRET="${{secrets.IOT_INVOKE_SECRET}}" \
            -e AUTH_URL="${{secrets.AUTH_URL}}" \
            -e AUTH_TRUST_HOST="true" \
            -e NEXTAUTH_SECRET="${{secrets.NEXTAUTH_SECRET}}" \
            "${{env.DOCKER_IMAGE}}:${{env.VERSION}}.${{env.TAG_VERSION}}"
